#######################################################################################
# Book settings
title : PoC For Documenting Spikes in JupyterBook
author: Patrick Kelley

# Information about where the book exists on the web
description: >-
  Trying out JupyterBook to see if we can use it fora knowledge base.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"
# notebook_interface            : "lab"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/pakelley/quantecon-jupyter-book
  path_to_book                : "spikes"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url             : https://mybinder.org
